<a href="https://colab.research.google.com/github/Abdul-Haseeb-boonig/Practice1/blob/main/Practice_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Difference between X_test, X_train, y_test, y_train

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [3]:
list(y)

[0, 1, 2, 3, 4]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.33,
                                                    random_state = 42)

In [7]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [8]:
y_train

[2, 0, 3]

In [9]:
X_test

array([[2, 3],
       [8, 9]])

In [10]:
y_test

[1, 4]

In [13]:
train_test_split(y, shuffle = False)

[[0, 1, 2], [3, 4]]

In [14]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import classification_report

df=pd.DataFrame({'X1' : [100,120,140,200,230,400,500,540,600,625],
                 'X2' : [14,15,22,24,23,31,33,35,40,40],
                 'Y' : [0,0,0,0,1,1,1,1,1,1]})

In [16]:
X = df[['X1','X2']]
y = df['Y']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.4,
                                                    random_state = 42)
X_train, X_test, y_train, y_test

(    X1  X2
 7  540  35
 2  140  22
 9  625  40
 4  230  23
 3  200  24
 6  500  33,
     X1  X2
 8  600  40
 1  120  15
 5  400  31
 0  100  14,
 7    1
 2    0
 9    1
 4    1
 3    0
 6    1
 Name: Y, dtype: int64,
 8    1
 1    0
 5    1
 0    0
 Name: Y, dtype: int64)

X_train : Includes all independent variables, that will be used for training. According to the above example the test size is 0.4 which means 60% of the observations that are independent

X_test : The rest 40% of independent variables that won't be used in the training phase instead will be used to test the accuracy of the model.

y_train : Includes the dependent variable that needs to predict the model with 60% of dependent variable going towards training.

y_test : The rest 40% of the depedent variable that is used to test the accuracy between the labels and the data.

In [ ]:
LR = LogisticRegression()
#for the trainig
LR.fit(X_train, y_train)
